baseURL = "/"
canonifyURLs = true
relativeURLs = false
languageCode = "it-it"
title = "Driven By Light"
theme = "hugo-PaperMod"


[params]
  author = "Tiziano Sapuppo"
  defaultTheme = "dark"
  disableThemeToggle = true

  ShowReadingTime = false
  ShowShareButtons = false
  ShowBreadCrumbs = false

  [params.label]
    text = "Driven By Light"
    icon = "/images/logo.png"
    iconHeight = 68

  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/drivenbylight.st?igsh=MXh6aHMybngxMDhoZA=="

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2

  [[menu.main]]
    name = "Servizi"
    url = "/servizi/"
    weight = 3

  [[menu.main]]
    name = "Contatti"
    url = "/contatti/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
